export { default as Loader } from "./Loader";
export { default as Navbar } from "./Navbar";
export { default as Footer } from "./Footer";
export { default as Artists } from "./Artists";
export { default as Collections } from "./Collections";
export { default as Info } from "./Info";
export { default as Transactions } from "./Transactions";
export { default as InfoNFT } from "./InfoNFT";
export { default as Welcome } from "./Welcome";
