export { default as Loader } from "../Page/Home/Loader";
export { default as Navbar } from "./Navbar";
export { default as Footer } from "./Footer";
export { default as Artists } from "../Page/Home/Artists";
export { default as Collections } from "../Page/Home/Collections";
export { default as Info } from "../Page/Home/Info";
export { default as Transactions } from "../Page/Home/Transactions";
export { default as InfoNFT } from "../Page/Home/InfoNFT";
export { default as Welcome } from "../Page/Home/Welcome";
